version: '3.8'

services:
  snippetbox:
    image: snippetbox:1
    container_name: snippetbox
    restart: unless-stopped
    ports: 
      - '4000:4000'
    environment:
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - DBNAME=${DBNAME}

  snippetbox_db:
    image: mysql:5.7
    container_name: snippetbox_db
    restart: unless-stopped
    ports: 
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_ROOT_PASSWORD: ${DBPASS}
    volumes: 
      - db-data:/var/lib/mysql

volumes: 
  db-data:
    driver: local